user_models:
  max_length_name: 50
  max_length_email: 255
  max_length_password: 6
sessions_controller:
  value_1: "1"
size:
  size_index: 50
  size_gravatar: 50
params:
  value_1: "1"
password:
  reset: 2
micro:
  max_length: 140
  size_image: 5
micro_view:
  size: 50
user_info:
  size: 50
show:
  size: 30

